"""In-memory demo data for the AI novel recommendation assistant.

The data intentionally mirrors the product questions in the README:
recent taste, high-retention similar readers, intro/content consistency,
drop risk, and reading-assistant summaries.
"""

from __future__ import annotations


USERS = [
    {
        "id": "user_xly",
        "nickname": "xlyyyd",
        "description": "番茄小说深度用户，近期偏好规则怪谈、强悬念、快节奏和主角智商在线。",
    },
    {
        "id": "user_mirror",
        "nickname": "镜中读者",
        "description": "和 user_xly 高度相似，也常在前三章快速判断是否弃读。",
    },
    {
        "id": "user_galaxy",
        "nickname": "银河档案员",
        "description": "偏好设定密度高、群像和世界观完整的作品。",
    },
]


BOOKS = [
    {
        "id": "book_001",
        "title": "午夜规则档案",
        "author": "鹿隐",
        "category": "规则怪谈",
        "status": "连载中",
        "word_count": 920000,
        "cover_theme": "violet",
        "intro": "凌晨零点，城市所有电梯同时出现第十三层。林澈必须在十条互相矛盾的规则里找到活路。",
        "positive_tags": ["规则怪谈", "强悬念", "主角智商在线", "快节奏", "伏笔密集"],
        "negative_tags": ["文笔偏白"],
        "hook_score": 9.1,
        "style_score": 8.6,
        "intro_consistency_score": 9.0,
        "quality_score": 8.8,
        "similar_reader_retention": 0.86,
        "summary": "前三章直接抛出异常规则和生存代价，主角通过观察规则漏洞完成第一次反杀。",
        "comments_signal": "相似读者普遍认为前三章钩子强，但文风偏直给。",
    },
    {
        "id": "book_002",
        "title": "旧城回声",
        "author": "江亭",
        "category": "悬疑脑洞",
        "status": "完结",
        "word_count": 740000,
        "cover_theme": "teal",
        "intro": "一座被遗忘的旧城每天重复同一天，女记者苏眠循着广播里的求救声追查失踪案。",
        "positive_tags": ["强悬念", "女性主角", "反套路", "情绪张力", "设定新颖"],
        "negative_tags": ["慢热"],
        "hook_score": 8.3,
        "style_score": 8.9,
        "intro_consistency_score": 8.7,
        "quality_score": 8.9,
        "similar_reader_retention": 0.78,
        "summary": "开篇氛围感强，谜团推进稳，适合能接受慢热悬疑的读者。",
        "comments_signal": "高分评论集中在反转和人物动机，但部分读者反馈前期节奏较慢。",
    },
    {
        "id": "book_003",
        "title": "宿舍求生手册",
        "author": "白日灯",
        "category": "规则怪谈",
        "status": "连载中",
        "word_count": 580000,
        "cover_theme": "crimson",
        "intro": "新生群里突然多出一份宿舍守则：晚上十点后不要回应上铺的呼吸声。",
        "positive_tags": ["规则怪谈", "前三章钩子强", "快节奏", "校园惊悚"],
        "negative_tags": ["套路重复", "人设单薄"],
        "hook_score": 8.8,
        "style_score": 7.2,
        "intro_consistency_score": 8.6,
        "quality_score": 7.3,
        "similar_reader_retention": 0.71,
        "summary": "钩子很强，事件密集，但角色塑造略工具化。",
        "comments_signal": "读者容易被开头吸引，但 20 章后有一定重复感。",
    },
    {
        "id": "book_004",
        "title": "她在末世开盲盒",
        "author": "风禾",
        "category": "女强末世",
        "status": "连载中",
        "word_count": 1030000,
        "cover_theme": "amber",
        "intro": "末世降临后，叶照获得盲盒系统，每一次选择都可能改变基地命运。",
        "positive_tags": ["女强", "经营", "爽点密集", "成长线"],
        "negative_tags": ["系统感强", "感情线弱"],
        "hook_score": 7.5,
        "style_score": 7.9,
        "intro_consistency_score": 8.2,
        "quality_score": 8.0,
        "similar_reader_retention": 0.62,
        "summary": "爽点稳定，适合女强经营流，但和近期规则怪谈兴趣不完全匹配。",
        "comments_signal": "喜欢经营成长的用户留存较好，悬疑脑洞用户点击后转化一般。",
    },
    {
        "id": "book_005",
        "title": "诡域清洁工",
        "author": "十九楼",
        "category": "都市异闻",
        "status": "完结",
        "word_count": 660000,
        "cover_theme": "slate",
        "intro": "城市里所有无法解释的异常，最后都由清洁工处理。新人周岚接到第一张红色工单。",
        "positive_tags": ["都市异闻", "设定新颖", "单元剧", "强悬念", "人物关系清晰"],
        "negative_tags": ["节奏中等"],
        "hook_score": 8.5,
        "style_score": 8.4,
        "intro_consistency_score": 8.9,
        "quality_score": 8.6,
        "similar_reader_retention": 0.82,
        "summary": "单元剧结构降低追更负担，异常设定和主线伏笔结合较好。",
        "comments_signal": "相似读者在第一个副本后继续阅读比例高。",
    },
    {
        "id": "book_006",
        "title": "神明退场之后",
        "author": "栖云",
        "category": "玄幻脑洞",
        "status": "连载中",
        "word_count": 1200000,
        "cover_theme": "indigo",
        "intro": "神明突然离开世界，所有被庇护的城市开始坠落，普通修补师被迫接管神谕。",
        "positive_tags": ["世界观完整", "群像", "设定密度高", "伏笔密集"],
        "negative_tags": ["慢热", "信息量大"],
        "hook_score": 7.8,
        "style_score": 9.0,
        "intro_consistency_score": 8.8,
        "quality_score": 9.1,
        "similar_reader_retention": 0.80,
        "summary": "设定成熟，长线伏笔强，但需要读者接受较高信息密度。",
        "comments_signal": "高质量长篇读者评价高，快餐爽文用户前期流失较多。",
    },
    {
        "id": "book_007",
        "title": "青铜列车",
        "author": "木辞",
        "category": "无限流",
        "status": "完结",
        "word_count": 850000,
        "cover_theme": "green",
        "intro": "每晚 23:17，一辆不存在的列车驶入站台。乘客必须在副本终点前找出隐藏车票。",
        "positive_tags": ["无限流", "强悬念", "快节奏", "反套路", "副本设计"],
        "negative_tags": ["角色死亡率高"],
        "hook_score": 9.0,
        "style_score": 8.5,
        "intro_consistency_score": 9.2,
        "quality_score": 8.7,
        "similar_reader_retention": 0.84,
        "summary": "副本目标清晰，危机感强，适合规则怪谈和无限流交叉偏好。",
        "comments_signal": "相似读者高留存，完结后评分稳定。",
    },
    {
        "id": "book_008",
        "title": "反派今天也在读档",
        "author": "简行",
        "category": "反套路",
        "status": "连载中",
        "word_count": 690000,
        "cover_theme": "rose",
        "intro": "反派每死一次就会读档回到第一章，他决定把所有剧情节点改成自己的主场。",
        "positive_tags": ["反套路", "主角智商在线", "爽点密集", "快节奏"],
        "negative_tags": ["轻喜剧", "逻辑偶有跳跃"],
        "hook_score": 8.7,
        "style_score": 8.2,
        "intro_consistency_score": 8.5,
        "quality_score": 8.1,
        "similar_reader_retention": 0.76,
        "summary": "读档机制带来明确爽点，适合想看高频反转的用户。",
        "comments_signal": "喜欢反套路主角的读者反馈好，严肃悬疑读者评价略分化。",
    },
    {
        "id": "book_009",
        "title": "我能听见弹幕剧透",
        "author": "三秋",
        "category": "都市脑洞",
        "status": "完结",
        "word_count": 510000,
        "cover_theme": "blue",
        "intro": "沈若突然能听见未来观众的弹幕，每条剧透都可能是陷阱。",
        "positive_tags": ["都市脑洞", "强悬念", "女性主角", "反套路"],
        "negative_tags": ["感情线争议", "中期节奏波动"],
        "hook_score": 8.2,
        "style_score": 8.1,
        "intro_consistency_score": 8.0,
        "quality_score": 7.9,
        "similar_reader_retention": 0.70,
        "summary": "设定抓人，但中期感情线可能影响悬疑阅读期待。",
        "comments_signal": "开头点击高，中期弃读多来自感情线争议。",
    },
    {
        "id": "book_010",
        "title": "失眠侦探事务所",
        "author": "钟北",
        "category": "都市悬疑",
        "status": "连载中",
        "word_count": 430000,
        "cover_theme": "orange",
        "intro": "只在凌晨营业的侦探事务所，专门处理梦境无法结束的人。",
        "positive_tags": ["都市悬疑", "单元剧", "情绪张力", "人物关系清晰"],
        "negative_tags": ["慢热", "文艺感强"],
        "hook_score": 7.7,
        "style_score": 8.7,
        "intro_consistency_score": 8.4,
        "quality_score": 8.4,
        "similar_reader_retention": 0.66,
        "summary": "氛围和文笔突出，推荐给想换口味的悬疑读者。",
        "comments_signal": "高质量但不够爽，强爽点用户可能低优先级。",
    },
    {
        "id": "book_011",
        "title": "契约钟声",
        "author": "舟渡",
        "category": "灵异契约",
        "status": "完结",
        "word_count": 780000,
        "cover_theme": "black",
        "intro": "每当钟声响起，契约人必须完成一项不可能任务，否则会失去一个记忆。",
        "positive_tags": ["强悬念", "设定新颖", "伏笔密集", "反套路"],
        "negative_tags": ["压抑", "信息量大"],
        "hook_score": 8.6,
        "style_score": 8.8,
        "intro_consistency_score": 8.9,
        "quality_score": 8.7,
        "similar_reader_retention": 0.79,
        "summary": "契约机制和记忆代价结合紧密，适合偏硬核悬疑脑洞的用户。",
        "comments_signal": "完结口碑稳定，适合向高质量悬疑拓展。",
    },
    {
        "id": "book_012",
        "title": "星际档案管理员",
        "author": "远星",
        "category": "科幻群像",
        "status": "连载中",
        "word_count": 970000,
        "cover_theme": "cyan",
        "intro": "银河档案馆被删除的每一页，都会在现实中抹去一个文明。",
        "positive_tags": ["科幻", "群像", "世界观完整", "设定密度高"],
        "negative_tags": ["慢热", "门槛较高"],
        "hook_score": 7.4,
        "style_score": 9.1,
        "intro_consistency_score": 8.7,
        "quality_score": 8.8,
        "similar_reader_retention": 0.68,
        "summary": "设定很强，但不是近期规则怪谈口味的最优先推荐。",
        "comments_signal": "硬科幻读者喜欢，轻松爽文用户转化较弱。",
    },
]


READING_EVENTS = [
    # Target user: recent intense interest in rule-based suspense.
    {"user_id": "user_xly", "book_id": "book_001", "event_type": "read_chapter", "duration_seconds": 13800, "progress": 0.72, "chapter_index": 86},
    {"user_id": "user_xly", "book_id": "book_001", "event_type": "add_bookshelf", "duration_seconds": 0, "progress": 0.72, "chapter_index": 86},
    {"user_id": "user_xly", "book_id": "book_006", "event_type": "read_chapter", "duration_seconds": 9400, "progress": 0.61, "chapter_index": 124},
    {"user_id": "user_xly", "book_id": "book_008", "event_type": "read_chapter", "duration_seconds": 7200, "progress": 0.48, "chapter_index": 53},
    {"user_id": "user_xly", "book_id": "book_004", "event_type": "abandon_book", "duration_seconds": 1300, "progress": 0.04, "chapter_index": 5},
    {"user_id": "user_xly", "book_id": "book_009", "event_type": "abandon_book", "duration_seconds": 2100, "progress": 0.12, "chapter_index": 14},
    # Similar readers.
    {"user_id": "user_mirror", "book_id": "book_001", "event_type": "read_chapter", "duration_seconds": 11800, "progress": 0.80, "chapter_index": 102},
    {"user_id": "user_mirror", "book_id": "book_003", "event_type": "read_chapter", "duration_seconds": 7600, "progress": 0.49, "chapter_index": 44},
    {"user_id": "user_mirror", "book_id": "book_005", "event_type": "read_chapter", "duration_seconds": 9200, "progress": 0.69, "chapter_index": 70},
    {"user_id": "user_mirror", "book_id": "book_007", "event_type": "read_chapter", "duration_seconds": 13200, "progress": 0.93, "chapter_index": 120},
    {"user_id": "user_mirror", "book_id": "book_010", "event_type": "abandon_book", "duration_seconds": 1200, "progress": 0.05, "chapter_index": 4},
    {"user_id": "user_galaxy", "book_id": "book_006", "event_type": "read_chapter", "duration_seconds": 14500, "progress": 0.76, "chapter_index": 151},
    {"user_id": "user_galaxy", "book_id": "book_011", "event_type": "read_chapter", "duration_seconds": 8700, "progress": 0.64, "chapter_index": 79},
    {"user_id": "user_galaxy", "book_id": "book_012", "event_type": "read_chapter", "duration_seconds": 9900, "progress": 0.68, "chapter_index": 88},
]


CHAPTERS = {
    "book_001": [
        {
            "id": "chapter_001_001",
            "title": "第1章 第十三层",
            "content": "凌晨零点，电梯屏幕亮起不存在的 13。林澈看到守则第一条：不要相信第一个和你说话的人。",
            "summary": "城市电梯出现第十三层，主角获得互相矛盾的生存守则，异常事件正式开始。",
            "key_events": ["电梯出现第十三层", "获得十条规则", "第一个异常人影出现"],
            "characters": ["林澈", "管理员"],
            "foreshadowing": ["规则第一条可能在误导主角", "第十三层并非固定空间"],
        },
        {
            "id": "chapter_001_002",
            "title": "第2章 红色按钮",
            "content": "林澈假装按下红色按钮，管理员第一次露出迟疑。他意识到规则不是限制，而是谈判筹码。",
            "summary": "主角通过假动作测试规则边界，发现管理员会被规则反向约束。",
            "key_events": ["测试红色按钮", "管理员露出破绽", "确认规则可被利用"],
            "characters": ["林澈", "管理员"],
            "foreshadowing": ["红色按钮可能连接真实出口"],
        },
    ],
    "book_005": [
        {
            "id": "chapter_005_001",
            "title": "第1章 红色工单",
            "content": "周岚在清洁车里发现红色工单：请在日出前擦掉 17 楼走廊尽头的脚印。",
            "summary": "新人清洁工接到第一张红色工单，被迫进入都市异常处理流程。",
            "key_events": ["红色工单出现", "异常脚印蔓延", "清洁队旧规则被提及"],
            "characters": ["周岚", "老许"],
            "foreshadowing": ["脚印方向和真实空间不一致"],
        }
    ],
    "book_007": [
        {
            "id": "chapter_007_001",
            "title": "第1章 23:17 的列车",
            "content": "车站广播报出不存在的班次，青铜色列车停在雾里，乘客名单上已经划掉三个人。",
            "summary": "青铜列车首次出现，乘客必须找到隐藏车票才能离开副本。",
            "key_events": ["不存在的列车进站", "乘客名单出现死亡标记", "隐藏车票规则公布"],
            "characters": ["许砚", "列车员"],
            "foreshadowing": ["车票可能不在乘客身上", "列车员知道更多副本规则"],
        }
    ],
}


FEEDBACK_OPTIONS = ["喜欢", "不感兴趣", "节奏太慢", "简介不符", "文笔不喜欢", "人设不行", "看过了", "加入书架"]


def get_book(book_id: str) -> dict | None:
    return next((book for book in BOOKS if book["id"] == book_id), None)

